# Generated by Django 2.2.6 on 2019-10-15 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancha', models.CharField(max_length=50, unique=True)),
                ('codigo_interno', models.CharField(max_length=30, unique=True)),
                ('tipo_cancha', models.CharField(max_length=20)),
                ('vestuario_disponible', models.CharField(max_length=2)),
                ('iluminacion', models.CharField(max_length=2)),
                ('cesped_sintetico', models.CharField(max_length=2)),
            ],
            options={
                'ordering': ('nombre_cancha',),
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=80)),
                ('turno_reserva', models.DateTimeField(unique=True)),
                ('reserva_creada', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canchas.Cancha')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('turno_reserva',),
            },
        ),
    ]
