# Generated by Django 2.2.6 on 2019-10-15 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_auto_20191015_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cancha',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='canchas.Cancha'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='empleado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
